### PR TITLE
Added gemfire-for-tas wan setups cert rotation procedure

### PR DESCRIPTION
**Pull request by ainani-vmw**
This PR:
 - Added support for cert rotation of WAN setups in Gemfire for TAS

### CODE REVIEW

**Comment by ainani-vmw** [comment]
@anita-flegg : Please have a look on this.

**Comment by anita-flegg** [comment]
Thanks for setting this up, @ainani -- I understand the request a lot better now. 

Looking at the changes in detail, I see that all of the changes are in the "Rotate the Services TLS CA and its leaf certificates" section. Rather than sending the reader out to the new topic 3 times, it might be better to reproduce this whole section in the new Gemfire-specific topic. 
This would make the linking much easier and I think the flow would be better for the reader.

What do you think?

**Comment by ainani-vmw** [comment]
> Thanks for setting this up, @ainani -- I understand the request a lot better now.
> 
> Looking at the changes in detail, I see that all of the changes are in the "Rotate the Services TLS CA and its leaf certificates" section. Rather than sending the reader out to the new topic 3 times, it might be better to reproduce this whole section in the new Gemfire-specific topic. This would make the linking much easier and I think the flow would be better for the reader.
> 
> What do you think?

Hi @anita-flegg 
I am fine with that.
Only concern is to maintain the duplicate content twice.

But if that's fine and will help user then we can do that

**Comment by anita-flegg** [comment]
@ainani , Note the new KB link (Broadcom): 
For more information, see [Cloud Controller fails to create service instance when there is a expired cert installed on the system](https://knowledge.broadcom.com/external/article?articleNumber=293888) in the Tanzu Support Knowledge Base.

**Comment by anita-flegg** [comment]
I have made these additions manually, so I won't be merging this PR.

Here are the changes on staging. Please review and let me know whether you need any changes before I publish it to production.
https://docs-staging.vmware.com/en/VMware-Tanzu-Operations-Manager/3.0/vmware-tanzu-ops-manager/security-pcf-infrastructure-advanced-certificate-rotation.html#rotate-the-services-tls-ca-and-its-leaf-certificates

Note the divergence of the 2 sections at "To rotate the Services TLS CA and its leaf certificates..."

**Pull request closed without merging**
