### PR TITLE
Fix: director config instructions

### PR DESCRIPTION
**Pull request by ctlong**
The checkboxes within OpsManager were updated in April to make this clear. These docs changes should now match the existing director config.

### CODE REVIEW

**Comment by ctlong** [comment]
We're not confident that this image is the right size/shape, could you please advise us on whether it needs to change? Thanks!

**Comment by anita-flegg** [comment]
Hi @ctlong, is there a reason the new screen shot shows 6 checkboxes rather than the 8 shown in the original? I notice the alt text still lists 8 checkboxes. The screenshot is much smaller than the original -- will it still be readable/legible in the output?

The alt text is very long -- if the checkboxes and their uses are already described in the text (I assume they are), then all this detail is not required in the alt text. This can result in repetition for those using screen readers.
Instead, the screenshot alt text should describe only relevant info that's available only in the graphic.
You might consider "The Director Config screen (dialog box?) is used to set the NTP Servers and the BOSH HM Forwarder Address, along with several configuration options." 
Or, if this information is also already completely covered by the surrounding text, you could use null alt text. Feel free to contact me if you have any questions.

**Comment by ctlong** [comment]
@anita-flegg we believe that we've addressed all of your requests in the two commits we've just added. Can you please have a look, and merge it if it looks good to you. :)

* Updated the image to be a similar size (and include all of the same checkboxes) as before.
* Updated the alt text to describe what the unique value of the image rather than reiterate the checkboxes.

**Comment by anita-flegg** [comment]
Thanks very much, Carson. Looks great. Since the screen reader tells the user that they are on an image, we don't need to add "screenshot of" or "photo of" etc. I made this minor change.

**Pull request merged**
